---
version: '3.8'

services:
  python:
    build: python
    ports:
      - 8080:80

  db:
    image: postgres:13.9
    env_file:
      - ./config/.env.db

  adminer:
    image: adminer
    ports:
      - 9000:8080